/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { useState } from 'react';
import { UidRecord, UidRarity } from '../types';
import { playClick, playSuccess, playAlert } from '../utils/audio';
import { Search, Copy, Trash2, Download, FileSpreadsheet, Check, RefreshCw } from 'lucide-react';

interface HistoryViewProps {
  uids: UidRecord[];
  onDeleteUid: (id: string) => void;
  onClearAll: () => void;
}

export default function HistoryView({ uids, onDeleteUid, onClearAll }: HistoryViewProps) {
  const [searchTerm, setSearchTerm] = useState('');
  const [filterRarity, setFilterRarity] = useState<string>('ALL');
  const [copiedId, setCopiedId] = useState<string | null>(null);

  const getRarityBadgeStyle = (rarity: UidRarity) => {
    switch (rarity) {
      case UidRarity.COMMON: return 'bg-emerald-950/40 text-emerald-400 border-emerald-800/20';
      case UidRarity.UNCOMMON: return 'bg-blue-950/40 text-blue-400 border-blue-800/20';
      case UidRarity.RARE: return 'bg-purple-950/40 text-purple-400 border-purple-800/20';
      case UidRarity.EPIC: return 'bg-red-950/40 text-red-500 border-red-800/20';
      case UidRarity.LEGENDARY: return 'bg-amber-950/55 text-amber-400 border-amber-800/40 animate-pulse';
      case UidRarity.MYTHIC: return 'bg-gradient-to-r from-red-950 via-purple-950 to-indigo-950 text-fuchsia-400 border-purple-500/30';
    }
  };

  // Filter list
  const filtered = uids.filter((item) => {
    const term = searchTerm.toLowerCase();
    const matchesSearch = 
      item.uid.toLowerCase().includes(term) ||
      item.email.toLowerCase().includes(term) ||
      item.generatedBy.toLowerCase().includes(term);

    const matchesRarity = filterRarity === 'ALL' || item.rarity === filterRarity;

    return matchesSearch && matchesRarity;
  });

  const handleCopyText = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopiedId(id);
    playSuccess();
    setTimeout(() => setCopiedId(null), 1500);
  };

  // EXPORT TO TXT
  const handleExportTxt = () => {
    playSuccess();
    const headline = `=========================================\n  KINGWAR UID GENERATOR EXPORT - TXT\n=========================================\nExported on: ${new Date().toLocaleString()}\nTotal Records: ${filtered.length}\nFormat: UID | GMAIL | PASSWORD | RARITY | CREATION_TIME\n\n`;
    
    const lines = filtered.map(item => 
      `${item.uid} | ${item.email} | ${item.password} | ${item.rarity} | ${item.timestamp}`
    ).join('\n');

    const blob = new Blob([headline + lines], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `kingwar_uids_${Date.now()}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  // EXPORT TO CSV
  const handleExportCsv = () => {
    playSuccess();
    const headers = 'UID,Gmail,Password,Rarity,GeneratedBy,Timestamp\n';
    const rows = filtered.map(item => 
      `"${item.uid}","${item.email}","${item.password}","${item.rarity}","${item.generatedBy}","${item.timestamp}"`
    ).join('\n');

    const blob = new Blob([headers + rows], { type: 'text/csv;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `kingwar_uids_${Date.now()}.csv`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex flex-col h-full space-y-4">
      {/* Search Header Bar & Exports */}
      <div className="bg-[#181818]/75 border border-white/5 rounded-lg p-4 flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        {/* Search controls */}
        <div className="flex flex-col sm:flex-row gap-3 w-full md:w-auto flex-1 max-w-2xl">
          <div className="relative flex-1">
            <span className="absolute inset-y-0 left-0 flex items-center pl-3 text-zinc-500 pointer-events-none">
              <Search size={14} />
            </span>
            <input
              type="text"
              placeholder="Search by UID, Gmail prefix or generated by..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full bg-[#121212] border border-white/10 hover:border-[#ff2424]/20 focus:border-[#ff2424] focus:ring-0 focus:outline-none rounded text-white text-xs pl-9 pr-4 py-2 font-mono transition"
            />
          </div>
          
          <div className="relative">
            <select
              value={filterRarity}
              onChange={(e) => {
                playClick();
                setFilterRarity(e.target.value);
              }}
              className="bg-[#121212] border border-white/10 hover:border-white/20 focus:outline-none text-white text-xs px-3 py-2 rounded font-mono appearance-none min-w-[130px] pr-8 cursor-pointer"
            >
              <option value="ALL">ALL RARITIES</option>
              <option value="COMMON">COMMON</option>
              <option value="UNCOMMON">UNCOMMON</option>
              <option value="RARE">RARE</option>
              <option value="EPIC">EPIC</option>
              <option value="LEGENDARY">LEGENDARY</option>
              <option value="MYTHIC">MYTHIC</option>
            </select>
            <div className="absolute inset-y-0 right-0 flex items-center pr-3 pointer-events-none text-zinc-500 text-[10px]">
              ▼
            </div>
          </div>
        </div>

        {/* Export buttons */}
        <div className="flex gap-2 w-full md:w-auto">
          <button
            onClick={handleExportTxt}
            disabled={filtered.length === 0}
            className="flex-1 md:flex-none flex items-center justify-center gap-1.5 px-3 py-2 bg-white/5 hover:bg-[#ff2424]/10 border border-white/10 hover:border-[#ff2424]/30 text-white font-mono text-[10px] uppercase rounded transition disabled:opacity-40 disabled:pointer-events-none cursor-pointer"
            title="Download TXT file"
          >
            <Download size={12} /> export txt
          </button>
          <button
            onClick={handleExportCsv}
            disabled={filtered.length === 0}
            className="flex-1 md:flex-none flex items-center justify-center gap-1.5 px-3 py-2 bg-[#ff2424]/10 hover:bg-[#ff2424] border border-[#ff2424]/40 text-[#ff2424] hover:text-white font-mono text-[10px] uppercase rounded transition disabled:opacity-40 disabled:pointer-events-none cursor-pointer"
            title="Download CSV file"
          >
            <FileSpreadsheet size={12} /> export csv
          </button>
        </div>
      </div>

      {/* Main Records Spreadsheet table */}
      <div className="flex-1 bg-[#181818]/75 border border-white/5 rounded-lg overflow-hidden flex flex-col min-h-[350px]">
        {/* Table wrapper */}
        <div className="flex-1 overflow-x-auto overflow-y-auto max-h-[480px] custom-scrollbar">
          <table className="w-full table-auto border-collapse text-left text-xs font-mono">
            <thead>
              <tr className="bg-[#121212] border-b border-white/5 text-[#9f9f9f] text-[9px] uppercase tracking-wider select-none">
                <th className="py-3 px-4 font-semibold">Fictitious UID</th>
                <th className="py-3 px-4 font-semibold">Simulated Gmail Link</th>
                <th className="py-3 px-4 font-semibold">Fictitious Password</th>
                <th className="py-3 px-4 font-semibold">Rarity Class</th>
                <th className="py-3 px-4 font-semibold">Created By</th>
                <th className="font-semibold text-right py-3 pr-6">Decryption actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-white/5 bg-transparent text-white/90">
              {filtered.length === 0 ? (
                <tr>
                  <td colSpan={6} className="text-center py-20 text-zinc-500">
                    <p className="font-mono text-xs">No simulated UID matching query found.</p>
                    <p className="text-[10px] text-[#ff2424] mt-1">Try resetting filter or searching another pattern</p>
                  </td>
                </tr>
              ) : (
                filtered.map((item) => (
                  <tr key={item.id} className="hover:bg-white/[0.02] transition-colors group">
                    <td className="py-2.5 px-4 font-bold tracking-widest text-[#ff2424] text-xs">
                      {item.uid}
                    </td>
                    <td className="py-2.5 px-4 text-zinc-400 text-xs">
                      {item.email}
                    </td>
                    <td className="py-2.5 px-4 text-zinc-500 text-xs select-all">
                      {item.password}
                    </td>
                    <td className="py-2.5 px-4">
                      <span className={`text-[8px] font-bold px-1.5 py-0.5 rounded border ${getRarityBadgeStyle(item.rarity)}`}>
                        {item.rarity}
                      </span>
                    </td>
                    <td className="py-2.5 px-4 text-zinc-500 text-[10px]">
                      {item.generatedBy}
                    </td>
                    <td className="py-2.5 px-4 text-right pr-6">
                      <div className="flex gap-2 justify-end opacity-60 group-hover:opacity-100 transition-opacity">
                        <button
                          onClick={() => handleCopyText(`UID: ${item.uid} | Gmail: ${item.email} | Pass: ${item.password}`, item.id)}
                          className="p-1 bg-white/5 hover:bg-[#ff2424]/10 text-zinc-500 hover:text-[#ff2424] border border-white/10 hover:border-[#ff2424]/30 rounded transition cursor-pointer"
                          title="Copy Decrypted Account Values"
                        >
                          {copiedId === item.id ? <Check size={11} className="text-emerald-400" /> : <Copy size={11} />}
                        </button>
                        <button
                          onClick={() => {
                            playAlert();
                            onDeleteUid(item.id);
                          }}
                          className="p-1 bg-white/5 hover:bg-rose-500/15 text-zinc-500 hover:text-rose-400 border border-white/10 hover:border-rose-500/30 rounded transition cursor-pointer"
                          title="Wipe Item Record"
                        >
                          <Trash2 size={11} />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
        
        {/* Table footer count */}
        <div className="bg-[#121212] border-t border-white/5 px-4 py-3 flex justify-between items-center text-[10px] text-[#9f9f9f] select-none">
          <div>
            Showing <span className="text-white font-semibold">{filtered.length}</span> of <span className="text-white font-semibold">{uids.length}</span> simulated accounts
          </div>
          {filtered.length > 0 && (
            <button
              onClick={() => {
                if (window.confirm("Do you absolutely want to wipe current simulator records?")) {
                  playAlert();
                  onClearAll();
                }
              }}
              className="text-[#ff2424] hover:underline"
            >
              Reset Database Cache
            </button>
          )}
        </div>
      </div>
    </div>
  );
}
